# Makefile for the Side-Channel Attack Detection project

.PHONY: pdf clean

# Build the IEEE paper PDF
pdf:
	cd report && latexmk -pdf -interaction=nonstopmode main.tex

# Clean auxiliary files generated by LaTeX
clean:
	cd report && latexmk -c
